"""
TALOS - the living chess studio.

TALOS is a desktop chess playing and training suite.  It carries the spirit of
Lucas Chess (huge training library, Elo-graded opponents, variant support) into
a modern interface, and adds two things Lucas never had:

  * **Battle Chess** - a procedurally animated 3D board where the pieces walk,
    duel and die instead of teleporting.
  * **The anarchy wing** - Anarchchess (the chess variant) and Anarchess (the
    tile-laying board game that imagines the land of Chess before kings).

The whole application identity lives in this module so it can be re-branded by
editing a handful of constants.
"""

#: Product name shown in the window title, menus, PGN headers and about box.
APP_NAME = "TALOS"

#: Short tagline used in window titles and the about box.
APP_TAGLINE = "The Living Chess Studio"

#: Version string.
APP_VERSION = "2.2.2"

#: Full display name, e.g. "TALOS - The Living Chess Studio".
APP_FULL_NAME = f"{APP_NAME} - {APP_TAGLINE}"

#: Used as the PGN ``Event``/``Site`` tag generated by the app.
APP_PGN_EVENT = f"{APP_NAME} friendly"
APP_PGN_SITE = f"{APP_NAME} local"

#: Reverse the board / naming of the two sides.
SIDE_NAMES = {True: "White", False: "Black"}

#: The person this build is credited to in the about dialog.
APP_CREDIT = (
    "Built as a modern successor to Lucas Chess (Lukas Monk, GPLv2).\n"
    "Battle Chess combat mode is a procedural homage to Battle Chess (1988,\n"
    "Interplay).  Anarchess follows the published rules of the abstract "
    "board game designed by Dimitris Grammenos (ICS-FORTH)."
)


def window_title(document: str = "") -> str:
    """Return ``"TALOS - document"`` or just ``"TALOS"``."""
    return f"{APP_NAME} - {document}" if document else APP_NAME
